### ISSUE TITLE
Display DoinIt- List

### ISSUE THREAD

**Issue by NilsHolthey** [NilsHolthey/capstone-project#10]
# Value Proposition

As a User
I need to see a list of my tasks in the section "doingIT"
to be able to get an overview of open todos.

# Description
![Bildschirmfoto 2022-05-16 um 10 47 43](https://user-images.githubusercontent.com/101572806/168554996-10b1e044-44bf-4642-8be3-71a2c9597291.png)

# Acceptance Criteria
- [ ] The tasks are displayed in a List, called "DoingIT"
- [ ] The tasks are displayed, labeled by "Title:"
- [ ] Each task should be visually separated
- [ ] All tasks should be displayed in vertical order

# Tasks

- [ ] Create a new branch "doingIt-list"
- [ ] Create a List component to render the static data in a "< ul >"
- [ ] fetch cards(title) with status: " doingIt" from data-structure
- [ ] Add to App
- [ ] Add Tests to check if the data was rendered correctly

# Complexity
S

**Comment by NilsHolthey** [comment]
Hey Anita,

thx for the review. I change the userStory
