### ISSUE TITLE
Display DidIt-List

### ISSUE THREAD

**Issue by NilsHolthey** [NilsHolthey/capstone-project#11]
# Value Proposition

As a User
I need to see a list of my tasks in the section "didIT"
to be able to get an overview of finished todos.

# Description

![Bildschirmfoto 2022-05-16 um 10 48 00](https://user-images.githubusercontent.com/101572806/168558409-e2cb40c4-c567-46b7-9a58-7c643e1faf6f.png)

# Acceptance Criteria
- [ ] The tasks are displayed in a List, called "DidIT"
- [ ] The List shoudl be rendered on page "DidIt"
- [ ] create new Page called Didit
- [ ] The tasks are displayed, value of key:"Title"
- [ ] Each task should be visually separated
- [ ] All tasks should be displayed in vertical order

# Tasks

- [ ] Create a new branch "didIt-list"
- [ ] Create a List component to render the static data in a "< ul >"
- [ ] render cards(title) with status: " didIt"  by using filter method before map
- [ ] create routing for Page Ditit and list #2 and list #10
- [ ] Add to App
- [ ] Add Tests to check if the data was rendered correctly

# Complexity
S

**Comment by anitaschiller** [comment]
Hey Nils,
some comments from my side:

**Acceptance Criteria**:
- I think it would be nice if your criteria would tell where the list should exactly be rendered. Below the 'doingit' list on the start page or on a different page? It's hard to tell from your Wireframe.

**Tasks**
- I think you can reuse your List component (from your last user story), so that you don't have to create a new one. Just the array that should be rendered is different. It would be nice if your Tasks reflected that. 
- Also, do you really have to fetch the cards again? Or might a different description of this task be more precise?

**Comment by NilsHolthey** [comment]
Hi Anita, thx for the review.

For the Acceptance Criteria i agree with you an I changed it. The next userstory will be the navbar, so hopefully it will be more clear how the different lists are arragened.

Concerning the tasks:
 - I think I will need three different list, in order to manage the droppable components with the react-dnd library. At least for the start.

**Comment by anitaschiller** [comment]
Alright, I'm not a react-dnd expert! 😉 If you need three different list components for it, then it's fine. But you can keep this in mind and do a refactoring in the end in case you realize that one component might actually be enough. 

If you shift the two "create" bullet points from your Acceptance Criteria to your Tasks section (the user doesn't care about the routing), the story looks good to me!
