### ISSUE TITLE
Display Navigation

### ISSUE THREAD

**Issue by NilsHolthey** [NilsHolthey/capstone-project#12]
# Value Proposition

As a user i need to navigate to the different Todo-Lists,
in order to see every List separately so i have an overview of my tasks status

# Description
![Bildschirmfoto 2022-05-16 um 11 10 33](https://user-images.githubusercontent.com/101572806/168575052-b0395589-5426-41bf-b6f1-88c33105647f.png)

# Acceptance Criteria

- [x] The Navigation (NavList) should be displayed above the Todo-List
- [x] Every item of the NavList should be separated visually
- [x] the active item should be underlined and have a different font color
- [x] each Item should be clickable
- [x] each item should link to its corresponding page
- [x] the user should be redirect to the corresponding page Onclick

# Tasks

(for developers team)

- [x] Create a Navigation Component 
- [ ] Implement routing via next/link
- [ ] Each  NavItem should be a button, type button
- [ ] each item should link to its corresponding page
- [x] Add basic styling
- [x] add to app

# Complexity

S

**Comment by julialoeschel** [comment]
Hey there. 
Your heading is missspelled ;) You might wanna change that. 
I assume your pages are already done at the time you are working on that story. 
also please delete the `...`at the end.
Other than that I think thats a good story :)
