### ISSUE TITLE
Display todos

### ISSUE THREAD

**Issue by NilsHolthey** [NilsHolthey/capstone-project#2]
# Value Proposition

As a User
I need to see a list of my tasks
to be able to get an overview of open todos.

# Description
![Bildschirmfoto 2022-05-11 um 10 05 39](https://user-images.githubusercontent.com/101572806/167800717-65564f21-7762-4cc7-9d07-d45536bb3d15.png)

# Acceptance Criteria
- [ ] The tasks are displayed in a List, called "DoIT"
- [ ] The tasks are displayed, labeled by "Title:"
- [ ] Each task should be visually separated
- [ ] All tasks should be displayed in vertical order

# Tasks

- [ ] Create a new branch "todo-list"
- [ ] Create a database with static data
- [ ] Create a new component to render the static data in a "< ul >"
- [ ] Create Card component

# Complexity

S

**Comment by aclaes** [comment]
Hi Nils,

great first user story. It is slim and precise. However, I have small remarks.

- I see at least two components: a card component and a list component to display the cards
- Please don’t forget to add tests to check if the data was rendered correctly
- You should not write “database“ in the „tasks“ section since you are not working with a database yet. I think the term “data structure” is more appropriate
