### ISSUE TITLE
Percentage-Overview  of Tasks

### ISSUE THREAD

**Issue by NilsHolthey** [NilsHolthey/capstone-project#25]
# Value Proposition

As  a user i need an overview of my todos in percent,
in order to have an better overview of my todos and of their proportional distribution.

# Description

![Bildschirmfoto 2022-05-29 um 08 49 55](https://user-images.githubusercontent.com/101572806/170855933-06490494-42c3-4ad6-8d7a-d1987ef14836.png)

# Acceptance Criteria

- [ ]  three circular charts should be displayed
- [ ]  charts are displayed in vertical order
- [ ] each chard has a different color
- [ ] chart display proportional distribution in percent
# Tasks

(for developers team)

- [ ]  create new branch
- [ ] create page "overview"
- [ ] create overview component
- [ ] create overview-svg component
- [ ] svg percentage is calculated with array.length
- [ ] add button to BottomNavigation
- [ ] add routing
- [ ] add to app

# Complexity
m
