### ISSUE TITLE
Update Form

### ISSUE THREAD

**Issue by NilsHolthey** [NilsHolthey/capstone-project#26]
# Value Proposition

As a user I want to add more information to my todos than just the title,
in order to have a more detailed view and understanding of my single todos.

# Description

![Bildschirmfoto 2022-05-29 um 08 59 48](https://user-images.githubusercontent.com/101572806/170856419-6527a8c4-e937-42c1-a9c8-8b12f285ff75.png)

# Acceptance Criteria

- [ ] the form should render four input-fields( Title, description, level and deadline)
- [ ] each input-field has a placeholder
- [ ] each input-field can be filled out
- [ ] input value will be added to the todo onSubmit

# Tasks

(for developers team)

- [ ] create new branch
- [ ] add input type text for description to form
- [ ] add input type dropdown for level to form
- [ ] add input type date for deadline to form
- [ ] add key value of all three to static date in useStore
- [ ] add all three to map function in grid
- [ ] add all three to todo component 
- [ ] add test
- [ ] add basic styling

# Complexity

M
