### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by NilsHolthey** [NilsHolthey/capstone-project#27]
# Value Proposition

As a Product-Owner I need a landing-page,  to display an promote my App.
 

# Description
![Bildschirmfoto 2022-05-31 um 21 00 07](https://user-images.githubusercontent.com/101572806/171264768-5ce8294e-92de-4575-8a33-bf7ba4aad25c.png)

# Acceptance Criteria

- [ ] A logo animation should start after loading the page.
- [ ] A button is diplayed.
- [ ] The button links to the todo page

# Tasks

(for developers team)

- [ ] create new branch
- [ ] create Logo svg in Figma
- [ ] create logo component
- [ ] calculate stroke-dasharray length with js
- [ ] add styling and animation

# Complexity
s
