### ISSUE TITLE
Create Card Component

### ISSUE THREAD

**Issue by NilsHolthey** [NilsHolthey/capstone-project#3]
# Value Proposition

As a User
I need to see every single  todo-card
to be able to get an overview of open todos.

# Description
![Bildschirmfoto 2022-05-11 um 09 52 30](https://user-images.githubusercontent.com/101572806/167804743-65710ef8-a6f0-44eb-b729-3449468499a0.png)

# Acceptance Criteria

- [ ] All cards should be displayed vertically
- [ ] All cards should contain the Title
- [ ] All cards should only be displayed once
- [ ] All cards should display static data

# Tasks

- [ ] Create new branch "feature-cards"
- [ ] Create component "Service/get-cards"
- [ ] fetch cards(title) from database
- [ ] render Cards
- [ ] ...

# Complexity

**Comment by aclaes** [comment]
Hi Nils,

this user story raises some questions for me. I’m not sure how this requirements fit with the other user story:

https://github.com/NilsHolthey/capstone-project/issues/2

I assume, this story describes a detailed view of a single todo item, while the other user story describes the list of all todo item – since this wireframe shows only a single todo item.

Is this right?
