### ISSUE TITLE
Update Dropzone

### ISSUE THREAD

**Issue by NilsHolthey** [NilsHolthey/capstone-project#30]
# Value Proposition

As a user i need to  send a single todo back to the previous list via drag and drop,
so I can correct wrongfully placed todos.
# Description
![Bildschirmfoto 2022-06-01 um 12 07 54](https://user-images.githubusercontent.com/101572806/171380729-e15f1559-627a-4c1b-a8db-cd9555a6254e.png)

# Acceptance Criteria

- [ ] on Page DoIT one dropzone is displayed
- [ ] on Page DoingIT two dropzones are displayed
- [ ] on Page DidIT one dropzone is displayed
- [ ] when dragging an Item on a dropzone the item will be deleted out  of the list and pushed into the corresponding list.

# Tasks

(for developers team)

- [ ] create new branch
- [ ] update move functions in usestore
- [ ] render two more dropzones
- [ ] resize dropzone
- [ ] add styling

# Complexity

s

**Comment by CJAkkuec** [comment]
Looking good! I'm not super sure if I'd agree with the complexity assessment, but I trust your ability to gauge the scope of your user stories. ;)

**Comment by NilsHolthey** [comment]
Thank you CJ, 
I already have two dropzones in my app...so almost copy paste ;)
