### ISSUE TITLE
Create ToDo Form

### ISSUE THREAD

**Issue by NilsHolthey** [NilsHolthey/capstone-project#4]
# Value Proposition

As a user I want to add single tasks/todos to my List
to be able to see my personal tasks

# Description

![Bildschirmfoto 2022-05-11 um 10 59 28](https://user-images.githubusercontent.com/101572806/167829700-97502093-cf22-4e80-8d05-a66089e34133.png)

# Acceptance Criteria

- [ ] Title Inputs is required, show warning if empty.
- [ ] An input field for the Title is displayed, labeled "Title",
- [ ] A button to submit the entry is displayed, labeled "Submit"
- [ ] After submitting the new entry will appear in the list of todos, labeled "DoIT"
- [ ] After submitting the new entry , the user will be redirected to the "home" page

# Tasks

(for developers team)

- [ ] create new Branch "feature-form"
- [ ] create Page " CardCreateForm"
- [ ] Add form fields with labels
- [ ] Create a button component
- [ ] Create a input component
- [ ] Mark "Title" field as required
- [ ] handle form fields with a state
- [ ] Write tests to check the field labels
- [ ] Write tests to check if the entry was added to the data structure

# Complexity

XL
