### ISSUE TITLE
Footer Navigation

### ISSUE THREAD

**Issue by NilsHolthey** [NilsHolthey/capstone-project#5]
# Value Proposition

As a user I need to be able to click on the Add toDo button, so I will be directed to the createToDo page

# Description
![Bildschirmfoto 2022-05-11 um 13 05 07](https://user-images.githubusercontent.com/101572806/167835301-649e30e9-e6e9-4bd5-9180-c9a4583c6981.png)

# Acceptance Criteria

- [ ] A navigation at the bottom of the page is visible with a Button to Add a ToDo
- [ ] The button will link to the CreateToDo Page
- [ ] the Button will navigate to the CreateToDo Page OnClick

# Tasks

- [ ] Create a Footer component
- [ ] Add a button to footer
- [ ] OnClick link to CreateToDo Page
- [ ] ...

# Complexity

S
